//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gen6RNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gen6RNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = SM遇敌乱数 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_cn {
            get {
                return ResourceManager.GetString("lang_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = SMEnco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_ao {
            get {
                object obj = ResourceManager.GetObject("personal_ao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁.
        /// </summary>
        internal static string text_Natures_cn {
            get {
                return ResourceManager.GetString("text_Natures_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_Natures_en {
            get {
                return ResourceManager.GetString("text_Natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_cn {
            get {
                return ResourceManager.GetString("text_Species_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精.
        /// </summary>
        internal static string text_Types_cn {
            get {
                return ResourceManager.GetString("text_Types_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_Types_en {
            get {
                return ResourceManager.GetString("text_Types_en", resourceCulture);
            }
        }
    }
}
