//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk3DSRNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pk3DSRNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_down {
            get {
                object obj = ResourceManager.GetObject("Arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_up {
            get {
                object obj = ResourceManager.GetObject("Arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_00 {
            get {
                object obj = ResourceManager.GetObject("Clock_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_01 {
            get {
                object obj = ResourceManager.GetObject("Clock_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_02 {
            get {
                object obj = ResourceManager.GetObject("Clock_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_03 {
            get {
                object obj = ResourceManager.GetObject("Clock_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_04 {
            get {
                object obj = ResourceManager.GetObject("Clock_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_05 {
            get {
                object obj = ResourceManager.GetObject("Clock_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_06 {
            get {
                object obj = ResourceManager.GetObject("Clock_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_07 {
            get {
                object obj = ResourceManager.GetObject("Clock_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_08 {
            get {
                object obj = ResourceManager.GetObject("Clock_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_09 {
            get {
                object obj = ResourceManager.GetObject("Clock_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_10 {
            get {
                object obj = ResourceManager.GetObject("Clock_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_11 {
            get {
                object obj = ResourceManager.GetObject("Clock_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_12 {
            get {
                object obj = ResourceManager.GetObject("Clock_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_13 {
            get {
                object obj = ResourceManager.GetObject("Clock_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_14 {
            get {
                object obj = ResourceManager.GetObject("Clock_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_15 {
            get {
                object obj = ResourceManager.GetObject("Clock_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_16 {
            get {
                object obj = ResourceManager.GetObject("Clock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_de {
            get {
                return ResourceManager.GetString("lang_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_fr {
            get {
                return ResourceManager.GetString("lang_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_ja {
            get {
                return ResourceManager.GetString("lang_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS乱数工 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_zh {
            get {
                return ResourceManager.GetString("lang_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NonShiny {
            get {
                object obj = ResourceManager.GetObject("NonShiny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_ao {
            get {
                object obj = ResourceManager.GetObject("personal_ao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_uu {
            get {
                object obj = ResourceManager.GetObject("personal_uu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shiny {
            get {
                object obj = ResourceManager.GetObject("Shiny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂ Nur
        ///♀ Nur.
        /// </summary>
        internal static string text_Genderratio_de {
            get {
                return ResourceManager.GetString("text_Genderratio_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderless
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂ Only
        ///♀ Only.
        /// </summary>
        internal static string text_Genderratio_en {
            get {
                return ResourceManager.GetString("text_Genderratio_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Género
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///Solo ♂
        ///Solo ♀.
        /// </summary>
        internal static string text_Genderratio_es {
            get {
                return ResourceManager.GetString("text_Genderratio_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderless
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂ Only
        ///♀ Only.
        /// </summary>
        internal static string text_Genderratio_fr {
            get {
                return ResourceManager.GetString("text_Genderratio_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無性別
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂のみ
        ///♀のみ.
        /// </summary>
        internal static string text_Genderratio_ja {
            get {
                return ResourceManager.GetString("text_Genderratio_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无性别
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///只有♂
        ///只有♀.
        /// </summary>
        internal static string text_Genderratio_zh {
            get {
                return ResourceManager.GetString("text_Genderratio_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Item
        ///Ewigstein
        ///Fatumknoten
        ///Machtgewicht
        ///Machtreif
        ///Machtgurt
        ///Machtlinse
        ///Machtband
        ///Machtkette.
        /// </summary>
        internal static string text_Items_de {
            get {
                return ResourceManager.GetString("text_Items_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item
        ///Everstone
        ///Destiny Knot
        ///Power Weight
        ///Power Bracer
        ///Power Belt
        ///Power Lens
        ///Power Band
        ///Power Anklet.
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ning煤n Objeto
        ///Piedra Eterna
        ///Lazo Destino
        ///Pesa Recia
        ///Brazal Recio
        ///Cinto Recio
        ///Lente Recia
        ///Banda Recia
        ///Franja Recia.
        /// </summary>
        internal static string text_Items_es {
            get {
                return ResourceManager.GetString("text_Items_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun
        ///Pierre Stase
        ///Nœud Destin
        ///Poids Pouvoir
        ///Poignée Pouvoir
        ///Ceinture Pouvoir
        ///Lentille Pouvoir
        ///Bandeau Pouvoir
        ///Chaîne Pouvoir.
        /// </summary>
        internal static string text_Items_fr {
            get {
                return ResourceManager.GetString("text_Items_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定なし
        ///変わらず
        ///赤い糸
        ///パワーウエイト
        ///パワーリスト
        ///パワーベルト
        ///パワーレンズ
        ///パワーバンド
        ///パワーアンクル.
        /// </summary>
        internal static string text_Items_ja {
            get {
                return ResourceManager.GetString("text_Items_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无道具
        ///不变之石
        ///红线
        ///力量负重-H
        ///力量护腕-A
        ///力量腰带-B
        ///力量镜-C
        ///力量束带-D
        ///力量护踝-S.
        /// </summary>
        internal static string text_Items_zh {
            get {
                return ResourceManager.GetString("text_Items_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Mysteriöser Ort
        ///
        ///Ferner Ort
        ///
        ///Route 1
        ///Hauholi-Stadtrand
        ///Route 1
        ///
        ///Route 3
        ///
        ///Route 2
        ///
        ///Kala’e-Bucht
        ///
        ///Meer von Mele-Mele
        ///
        ///Hauholi City
        ///Strandpromenade
        ///Hauholi City
        ///Einkaufsviertel
        ///Hauholi City
        ///Hafen
        ///Lili’i
        ///
        ///Mahalo-Bergpfad
        ///
        ///Mahalo-Bergpfad
        ///Hängebrücke
        ///Ruinen des Krieges
        ///
        ///Ruinen des Krieges
        ///[~ 33]
        ///Tenkarat-Hügel
        ///
        ///Tenkarat-Hügel
        ///Zentraler Felskessel
        ///Hauholi-Friedhof
        ///
        ///Mele-Mele-Blumenmeer
        ///
        ///Meereshöhle
        ///
        ///Beerenfelder
        ///
        ///Vegetationshöhle
        ///Prüfungsbereich
        ///Vegetati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_de {
            get {
                return ResourceManager.GetString("text_Location_sm_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ——————
        ///
        ///Mystery Zone
        ///
        ///Faraway Place
        ///
        ///Route 1
        ///Hau’oli Outskirts
        ///Route 1
        ///
        ///Route 3
        ///
        ///Route 2
        ///
        ///Kala’e Bay
        ///
        ///Melemele Sea
        ///
        ///Hau’oli City
        ///Beachfront
        ///Hau’oli City
        ///Shopping District
        ///Hau’oli City
        ///Marina
        ///Iki Town
        ///
        ///Mahalo Trail
        ///
        ///Mahalo Trail
        ///Plank Bridge
        ///Ruins of Conflict
        ///
        ///Ruins of Conflict
        ///[~ 33]
        ///Ten Carat Hill
        ///
        ///Ten Carat Hill
        ///Farthest Hollow
        ///Hau’oli Cemetery
        ///
        ///Melemele Meadow
        ///
        ///Seaward Cave
        ///
        ///Berry Fields
        ///
        ///Verdant Cavern
        ///Trial Site
        ///Verdant Cavern
        ///Totem’s Den
        ///Route 4
        ///
        ///Rou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_en {
            get {
                return ResourceManager.GetString("text_Location_sm_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －
        ///
        ///Lugar misterioso
        ///
        ///Lugar lejano
        ///
        ///Ruta 1
        ///Afueras de Hauoli
        ///Ruta 1
        ///
        ///Ruta 3
        ///
        ///Ruta 2
        ///
        ///Bahía Kalae
        ///
        ///Mar de Melemele
        ///
        ///Ciudad Hauoli
        ///Paseo Marítimo
        ///Ciudad Hauoli
        ///Zona Comercial
        ///Ciudad Hauoli
        ///Puerto
        ///Pueblo Lilii
        ///
        ///Senda Mahalo
        ///
        ///Senda Mahalo
        ///Puente Colgante
        ///Ruinas de la Guerra
        ///
        ///Ruinas de la Guerra
        ///[~ 33]
        ///Colina Dequilate
        ///
        ///Colina Dequilate
        ///Caldera Remota
        ///Cementerio de Hauoli
        ///
        ///Jardines de Melemele
        ///
        ///Gruta Unemar
        ///
        ///Huerto de Bayas
        ///
        ///Cueva Sotobosque
        ///Sala de la Prueba
        ///Cueva  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_es {
            get {
                return ResourceManager.GetString("text_Location_sm_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Endroit mystérieux
        ///
        ///Endroit lointain
        ///
        ///Route 1
        ///Abords d’Ekaeka
        ///Route 1
        ///
        ///Route 3
        ///
        ///Route 2
        ///
        ///Baie de Kala’e
        ///
        ///Mer de Mele-Mele
        ///
        ///Ekaeka
        ///Plage
        ///Ekaeka
        ///Zone commerciale
        ///Ekaeka
        ///Port
        ///Lili’i
        ///
        ///Sentier de Mahalo
        ///
        ///Sentier de Mahalo
        ///Pont suspendu
        ///Ruines du Conflit
        ///
        ///Ruines du Conflit
        ///[~ 33]
        ///Colline Dicarat
        ///
        ///Colline Dicarat
        ///Caldeira Toutofon
        ///Cimetière d’Ekaeka
        ///
        ///Jardin de Mele-Mele
        ///
        ///Grotte Verlamer
        ///
        ///Champ de Baies
        ///
        ///Grotte Verdoyante
        ///Zone de l’Épreuve
        ///Grotte Verdoyant [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_fr {
            get {
                return ResourceManager.GetString("text_Location_sm_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///なぞのばしょ
        ///
        ///とおいばしょ
        ///
        ///１ばんどうろ
        ///ハウオリシティはずれ
        ///１ばんどうろ
        ///
        ///３ばんどうろ
        ///
        ///２ばんどうろ
        ///
        ///カーラエわん
        ///
        ///メレメレかい
        ///
        ///ハウオリシティ
        ///ビーチサイドエリア
        ///ハウオリシティ
        ///ショッピングエリア
        ///ハウオリシティ
        ///ポートエリア
        ///リリィタウン
        ///
        ///マハロさんどう
        ///
        ///マハロさんどう
        ///つりばし
        ///いくさのいせき
        ///
        ///いくさのいせき
        ///[~ 33]
        ///テンカラットヒル
        ///
        ///テンカラットヒル
        ///さいおうくうどう
        ///ハウオリれいえん
        ///
        ///メレメレのはなぞの
        ///
        ///うみつなぎのどうけつ
        ///
        ///きのみばたけ
        ///
        ///しげみのどうくつ
        ///しれんのま
        ///しげみのどうくつ
        ///ぬしのま
        ///４ばんどうろ
        ///
        ///５ばんどうろ
        ///
        ///６ばんどうろ
        ///
        ///７ばんどうろ
        ///
        ///８ばんどうろ
        ///
        ///９ばんどうろ
        ///
        ///ハノハノリゾート
        ///
        ///ハノハノビーチ
        ///
        ///アーカラのはなぞの
        ///
        ///オハナタウン
        ///
        ///カンタイシティ
        ///
        ///コニコシティ
        ///
        ///ロイヤルアベニュー
        ///
        ///メモリアルヒル
        ///
        ///オハナぼくじょう
        ///
        ///[~ 80]
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_ja {
            get {
                return ResourceManager.GetString("text_Location_sm_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///神秘的地方
        ///
        ///遥远的地方
        ///
        ///１号道路
        ///好奥乐市郊
        ///１号道路
        ///
        ///３号道路
        ///
        ///２号道路
        ///
        ///卡拉蔚湾
        ///
        ///美乐美乐海
        ///
        ///好奥乐市
        ///海滩区
        ///好奥乐市
        ///商业区
        ///好奥乐市
        ///港口区
        ///利利小镇
        ///
        ///马哈罗山路
        ///
        ///马哈罗山路
        ///吊桥
        ///战争遗迹
        ///
        ///战争遗迹
        ///[~ 33]
        ///十克拉山丘
        ///
        ///十克拉山丘
        ///最深处的空洞
        ///好奥乐墓园
        ///
        ///美乐美乐花园
        ///
        ///通海洞穴
        ///
        ///树果园
        ///
        ///葱郁洞窟
        ///考验之地
        ///葱郁洞窟
        ///霸主居处
        ///４号道路
        ///
        ///５号道路
        ///
        ///６号道路
        ///
        ///７号道路
        ///
        ///８号道路
        ///
        ///９号道路
        ///
        ///豪诺豪诺度假地
        ///
        ///豪诺豪诺海滩
        ///
        ///阿卡拉花园
        ///
        ///欧哈纳镇
        ///
        ///慷待市
        ///
        ///可霓可市
        ///
        ///皇家大道
        ///
        ///回忆之丘
        ///
        ///欧哈纳牧场
        ///
        ///[~ 80]
        ///
        ///维拉火山公园
        ///
        ///维拉火山公园
        ///霸主居处
        ///潺潺之丘
        ///
        ///潺潺之丘
        ///霸主居处
        ///树荫丛林
        ///
        ///生命遗迹
        ///
        ///阿卡拉岛郊外
        ///
        ///[~ 96]
        ///[~ 97]
        ///[~ 98]
        ///[~ 99]
        ///地鼠隧道
        ///
        ///豪诺豪诺度假地
        ///
        ///皇家巨蛋 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_zh {
            get {
                return ResourceManager.GetString("text_Location_sm_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Mysteriöser Ort
        ///
        ///Entfernter Ort
        ///
        ///Escissia
        ///
        ///Route 1
        ///Escissia-Pfad
        ///Aquarellia
        ///
        ///Route 2
        ///Progrès-Weg
        ///Nouvaria-Wald
        ///
        ///Route 3
        ///Ouvert-Weg
        ///Nouvaria City
        ///
        ///Route 4
        ///Parterre-Weg
        ///Illumina City
        ///
        ///Prismaturm
        ///
        ///Labor von Flordelis
        ///
        ///Route 5
        ///Coteau-Weg
        ///Vanitéa
        ///
        ///Château Tristesse
        ///
        ///Route 6
        ///Palais-Allee
        ///Magnum-Opus-Palast
        ///
        ///Route 7
        ///Rivière-Promenade
        ///Relievera City
        ///
        ///Route 8
        ///Muraille-Küstenpfad
        ///Petrophia
        ///
        ///Route 9
        ///Rihorn-Pass
        ///Kampfschloss
        ///
        ///Route 10
        ///Menhir-Weg
        ///Cromlexia        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_de {
            get {
                return ResourceManager.GetString("text_Location_xy_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ——————
        ///
        ///Mystery Zone
        ///
        ///Faraway Place
        ///
        ///Vaniville Town
        ///
        ///Route 1
        ///Vaniville Pathway
        ///Aquacorde Town
        ///
        ///Route 2
        ///Avance Trail
        ///Santalune Forest
        ///
        ///Route 3
        ///Ouvert Way
        ///Santalune City
        ///
        ///Route 4
        ///Parterre Way
        ///Lumiose City
        ///
        ///Prism Tower
        ///
        ///Lysandre Labs
        ///
        ///Route 5
        ///Versant Road
        ///Camphrier Town
        ///
        ///Shabboneau Castle
        ///
        ///Route 6
        ///Palais Lane
        ///Parfum Palace
        ///
        ///Route 7
        ///Rivière Walk
        ///Cyllage City
        ///
        ///Route 8
        ///Muraille Coast
        ///Ambrette Town
        ///
        ///Route 9
        ///Spikes Passage
        ///Battle Chateau
        ///
        ///Route 10
        ///Menhir Trail
        ///Geo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_en {
            get {
                return ResourceManager.GetString("text_Location_xy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －
        ///
        ///Lugar misterioso
        ///
        ///Lugar lejano
        ///
        ///Pueblo Boceto
        ///
        ///Ruta 1
        ///Sendero Boceto
        ///Pueblo Acuarela
        ///
        ///Ruta 2
        ///Vía del Avance
        ///Bosque de Novarte
        ///
        ///Ruta 3
        ///Senda Despejada
        ///Ciudad Novarte
        ///
        ///Ruta 4
        ///Senda del Parterre
        ///Ciudad Luminalia
        ///
        ///Torre Prisma
        ///
        ///Laboratorios Lysson
        ///
        ///Ruta 5
        ///Vía Repecho
        ///Pueblo Vánitas
        ///
        ///Castillo Caduco
        ///
        ///Ruta 6
        ///Alameda del Palacio
        ///Palacio Cénit
        ///
        ///Ruta 7
        ///Paseo de la Ribera
        ///Ciudad Relieve
        ///
        ///Ruta 8
        ///Muralla Costera
        ///Pueblo Petroglifo
        ///
        ///Ruta 9
        ///Paso de Rhyhorn
        ///Bastión Batalla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_es {
            get {
                return ResourceManager.GetString("text_Location_xy_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///Endroit Mystérieux
        ///
        ///Endroit Lointain
        ///
        ///Bourg Croquis
        ///
        ///Route 1
        ///Sentier Croquis
        ///Quarellis
        ///
        ///Route 2
        ///Chemin Progrès
        ///Forêt de Neuvartault
        ///
        ///Route 3
        ///Chemin Ouvert
        ///Neuvartault
        ///
        ///Route 4
        ///Route Fleurie
        ///Illumis
        ///
        ///Tour Prismatique
        ///
        ///Labos Lysandre
        ///
        ///Route 5
        ///Chemin du Versant
        ///Fort-Vanitas
        ///
        ///Fort de Vanitas
        ///
        ///Route 6
        ///Allée du Palais
        ///Palais Chaydeuvre
        ///
        ///Route 7
        ///Chemin des Berges
        ///Relifac-le-Haut
        ///
        ///Route 8
        ///Falaise Muraille
        ///Roche-sur-Gliffe
        ///
        ///Route 9
        ///Piste Piquante
        ///Château de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_fr {
            get {
                return ResourceManager.GetString("text_Location_xy_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///なぞのばしょ
        ///
        ///とおいばしょ
        ///
        ///アサメタウン
        ///
        ///１ばんどうろ
        ///アサメのこみち
        ///メイスイタウン
        ///
        ///２ばんどうろ
        ///アバンセどおり
        ///ハクダンのもり
        ///
        ///３ばんどうろ
        ///ウベールどおり
        ///ハクダンシティ
        ///
        ///４ばんどうろ
        ///パルテールかいどう
        ///ミアレシティ
        ///
        ///プリズムタワー
        ///
        ///フラダリラボ
        ///
        ///５ばんどうろ
        ///ベルサンどおり
        ///コボクタウン
        ///
        ///ショボンヌじょう
        ///
        ///６ばんどうろ
        ///パレのなみきみち
        ///パルファムきゅうでん
        ///
        ///７ばんどうろ
        ///リビエールライン
        ///ショウヨウシティ
        ///
        ///８ばんどうろ
        ///ミュライユかいがん
        ///コウジンタウン
        ///
        ///９ばんどうろ
        ///トゲトゲさんどう
        ///バトルシャトー
        ///
        ///１０ばんどうろ
        ///メンヒルロード
        ///セキタイタウン
        ///
        ///１１ばんどうろ
        ///ミロワールどおり
        ///うつしみのどうくつ
        ///
        ///シャラシティ
        ///
        ///マスタータワー
        ///
        ///１２ばんどうろ
        ///フラージュどおり
        ///ヒヨクシティ
        ///
        ///１３ばんどうろ
        ///ミアレのこうや
        ///１４ばんどうろ
        ///クノエのりんどう
        ///クノエシティ
        ///
        ///ボールこうじょう
        ///
        ///１５ばん [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_ja {
            get {
                return ResourceManager.GetString("text_Location_xy_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------
        ///
        ///神秘的地方
        ///
        ///遥远的地方
        ///
        ///朝香镇
        ///
        ///1号道路
        ///卡洛斯
        ///美川镇
        ///
        ///2号道路
        ///前进通道
        ///白檀森林
        ///
        ///3号道路
        ///开展通道
        ///白檀市
        ///
        ///4号道路
        ///花坛街道
        ///密阿雷市
        ///
        ///密阿雷道馆
        ///
        ///弗拉达利实验室
        ///
        ///5号道路
        ///斜坡通道
        ///古木镇
        ///
        ///休波努城堡
        ///
        ///6号道路
        ///宫殿林荫道
        ///香水宫殿
        ///
        ///7号道路
        ///河川直路
        ///遥香市
        ///
        ///8号道路
        ///城墙海岸
        ///古香镇
        ///
        ///9号道路
        ///刺刺山道
        ///对战古堡
        ///
        ///10号道路
        ///石柱之路
        ///石林镇
        ///
        ///11号道路
        ///明镜通道
        ///映身洞窟
        ///
        ///娑罗市
        ///
        ///精通塔
        ///
        ///12号道路
        ///牧草通道
        ///海翼市
        ///
        ///13号道路
        ///密阿雷荒野
        ///14号道路
        ///香薰林道
        ///香薰市
        ///
        ///宝贝球工厂
        ///
        ///15号道路
        ///褐棕通道
        ///雪风镇
        ///
        ///16号道路
        ///忧郁通道
        ///[~ 80]
        ///[~ 81]
        ///冰霜洞穴
        ///
        ///17号道路
        ///象牙猪路
        ///百刻市
        ///
        ///18号道路
        ///狭谷通道
        ///水涟镇
        ///
        ///19号道路
        ///巨谷通道
        ///映雪市
        ///
        ///20号道路
        ///迷幻森林
        ///神奇宝贝村庄
        ///
        ///21号道路
        ///最后通道 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_zh {
            get {
                return ResourceManager.GetString("text_Location_xy_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust
        ///Solo
        ///Mutig
        ///Hart
        ///Frech
        ///Kühn
        ///Sanft
        ///Locker
        ///Pfiffig
        ///Lasch
        ///Scheu
        ///Hastig
        ///Ernst
        ///Froh
        ///Naiv
        ///Mäßig
        ///Mild
        ///Ruhig
        ///Zaghaft
        ///Hitzig
        ///Still
        ///Zart
        ///Forsch
        ///Sacht
        ///Kauzig.
        /// </summary>
        internal static string text_Natures_de {
            get {
                return ResourceManager.GetString("text_Natures_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_Natures_en {
            get {
                return ResourceManager.GetString("text_Natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuerte
        ///Huraña
        ///Audaz
        ///Firme
        ///Pícara
        ///Osada
        ///Dócil
        ///Plácida
        ///Agitada
        ///Floja
        ///Miedosa
        ///Activa
        ///Seria
        ///Alegre
        ///Ingenua
        ///Modesta
        ///Afable
        ///Mansa
        ///Tímida
        ///Alocada
        ///Serena
        ///Amable
        ///Grosera
        ///Cauta
        ///Rara.
        /// </summary>
        internal static string text_Natures_es {
            get {
                return ResourceManager.GetString("text_Natures_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardi
        ///Solo
        ///Brave
        ///Rigide
        ///Mauvais
        ///Assuré
        ///Docile
        ///Relax
        ///Malin
        ///Lâche
        ///Timide
        ///Pressé
        ///Sérieux
        ///Jovial
        ///Naïf
        ///Modeste
        ///Doux
        ///Discret
        ///Pudique
        ///Foufou
        ///Calme
        ///Gentil
        ///Malpoli
        ///Prudent
        ///Bizarre.
        /// </summary>
        internal static string text_Natures_fr {
            get {
                return ResourceManager.GetString("text_Natures_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to がんばりや
        ///さみしがり
        ///ゆうかん
        ///いじっぱり
        ///やんちゃ
        ///ずぶとい
        ///すなお
        ///のんき
        ///わんぱく
        ///のうてんき
        ///おくびょう
        ///せっかち
        ///まじめ
        ///ようき
        ///むじゃき
        ///ひかえめ
        ///おっとり
        ///れいせい
        ///てれや
        ///うっかりや
        ///おだやか
        ///おとなしい
        ///なまいき
        ///しんちょう
        ///きまぐれ.
        /// </summary>
        internal static string text_Natures_ja {
            get {
                return ResourceManager.GetString("text_Natures_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁.
        /// </summary>
        internal static string text_Natures_zh {
            get {
                return ResourceManager.GetString("text_Natures_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei
        ///Bisasam
        ///Bisaknosp
        ///Bisaflor
        ///Glumanda
        ///Glutexo
        ///Glurak
        ///Schiggy
        ///Schillok
        ///Turtok
        ///Raupy
        ///Safcon
        ///Smettbo
        ///Hornliu
        ///Kokuna
        ///Bibor
        ///Taubsi
        ///Tauboga
        ///Tauboss
        ///Rattfratz
        ///Rattikarl
        ///Habitak
        ///Ibitak
        ///Rettan
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandan
        ///Sandamer
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Piepi
        ///Pixi
        ///Vulpix
        ///Vulnona
        ///Pummeluff
        ///Knuddeluff
        ///Zubat
        ///Golbat
        ///Myrapla
        ///Duflor
        ///Giflor
        ///Paras
        ///Parasek
        ///Bluzuk
        ///Omot
        ///Digda
        ///Digdri
        ///Mauzi
        ///Snobilikat
        ///Enton
        ///Entoron
        ///Menki
        ///Rasaff
        ///Fukano
        ///Arka [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_de {
            get {
                return ResourceManager.GetString("text_Species_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huevo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_es {
            get {
                return ResourceManager.GetString("text_Species_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Œuf
        ///Bulbizarre
        ///Herbizarre
        ///Florizarre
        ///Salamèche
        ///Reptincel
        ///Dracaufeu
        ///Carapuce
        ///Carabaffe
        ///Tortank
        ///Chenipan
        ///Chrysacier
        ///Papilusion
        ///Aspicot
        ///Coconfort
        ///Dardargnan
        ///Roucool
        ///Roucoups
        ///Roucarnage
        ///Rattata
        ///Rattatac
        ///Piafabec
        ///Rapasdepic
        ///Abo
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sabelette
        ///Sablaireau
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Mélofée
        ///Mélodelfe
        ///Goupix
        ///Feunard
        ///Rondoudou
        ///Grodoudou
        ///Nosferapti
        ///Nosferalto
        ///Mystherbe
        ///Ortide
        ///Rafflesia
        ///Paras
        ///Parasect
        ///Mimitoss
        ///Aéromite
        ///Taupiqu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_fr {
            get {
                return ResourceManager.GetString("text_Species_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タマゴ
        ///フシギダネ
        ///フシギソウ
        ///フシギバナ
        ///ヒトカゲ
        ///リザード
        ///リザードン
        ///ゼニガメ
        ///カメール
        ///カメックス
        ///キャタピー
        ///トランセル
        ///バタフリー
        ///ビードル
        ///コクーン
        ///スピアー
        ///ポッポ
        ///ピジョン
        ///ピジョット
        ///コラッタ
        ///ラッタ
        ///オニスズメ
        ///オニドリル
        ///アーボ
        ///アーボック
        ///ピカチュウ
        ///ライチュウ
        ///サンド
        ///サンドパン
        ///ニドラン♀
        ///ニドリーナ
        ///ニドクイン
        ///ニドラン♂
        ///ニドリーノ
        ///ニドキング
        ///ピッピ
        ///ピクシー
        ///ロコン
        ///キュウコン
        ///プリン
        ///プクリン
        ///ズバット
        ///ゴルバット
        ///ナゾノクサ
        ///クサイハナ
        ///ラフレシア
        ///パラス
        ///パラセクト
        ///コンパン
        ///モルフォン
        ///ディグダ
        ///ダグトリオ
        ///ニャース
        ///ペルシアン
        ///コダック
        ///ゴルダック
        ///マンキー
        ///オコリザル
        ///ガーディ
        ///ウインディ
        ///ニョロモ
        ///ニョロゾ
        ///ニョロボン
        ///ケーシィ
        ///ユンゲラー
        ///フーディン
        ///ワンリキー
        ///ゴーリキー
        ///カイリキー
        ///マダツボミ
        ///ウツドン
        ///ウツボット
        ///メノクラゲ
        ///ドククラゲ
        ///イシツブテ
        ///ゴローン
        ///ゴローニャ
        ///ポニータ
        ///ギャロップ
        ///ヤ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_ja {
            get {
                return ResourceManager.GetString("text_Species_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_zh {
            get {
                return ResourceManager.GetString("text_Species_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Kampf
        ///Flug
        ///Gift
        ///Boden
        ///Gestein
        ///Käfer
        ///Geist
        ///Stahl
        ///Feuer
        ///Wasser
        ///Pflanze
        ///Elektro
        ///Psycho
        ///Eis
        ///Drache
        ///Unlicht
        ///Fee.
        /// </summary>
        internal static string text_Types_de {
            get {
                return ResourceManager.GetString("text_Types_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_Types_en {
            get {
                return ResourceManager.GetString("text_Types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Lucha
        ///Volador
        ///Veneno
        ///Tierra
        ///Roca
        ///Bicho
        ///Fantasma
        ///Acero
        ///Fuego
        ///Agua
        ///Planta
        ///Eléctrico
        ///Psíquico
        ///Hielo
        ///Dragón
        ///Siniestro
        ///Hada.
        /// </summary>
        internal static string text_Types_es {
            get {
                return ResourceManager.GetString("text_Types_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Combat
        ///Vol
        ///Poison
        ///Sol
        ///Roche
        ///Insecte
        ///Spectre
        ///Acier
        ///Feu
        ///Eau
        ///Plante
        ///Électrik
        ///Psy
        ///Glace
        ///Dragon
        ///Ténèbres
        ///Fée.
        /// </summary>
        internal static string text_Types_fr {
            get {
                return ResourceManager.GetString("text_Types_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ノーマル
        ///かくとう
        ///ひこう
        ///どく
        ///じめん
        ///いわ
        ///むし
        ///ゴースト
        ///はがね
        ///ほのお
        ///みず
        ///くさ
        ///でんき
        ///エスパー
        ///こおり
        ///ドラゴン
        ///あく
        ///フェアリー.
        /// </summary>
        internal static string text_Types_ja {
            get {
                return ResourceManager.GetString("text_Types_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精.
        /// </summary>
        internal static string text_Types_zh {
            get {
                return ResourceManager.GetString("text_Types_zh", resourceCulture);
            }
        }
    }
}
