//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pk3DSRNGTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pk3DSRNGTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_00 {
            get {
                object obj = ResourceManager.GetObject("Clock_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_01 {
            get {
                object obj = ResourceManager.GetObject("Clock_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_02 {
            get {
                object obj = ResourceManager.GetObject("Clock_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_03 {
            get {
                object obj = ResourceManager.GetObject("Clock_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_04 {
            get {
                object obj = ResourceManager.GetObject("Clock_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_05 {
            get {
                object obj = ResourceManager.GetObject("Clock_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_06 {
            get {
                object obj = ResourceManager.GetObject("Clock_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_07 {
            get {
                object obj = ResourceManager.GetObject("Clock_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_08 {
            get {
                object obj = ResourceManager.GetObject("Clock_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_09 {
            get {
                object obj = ResourceManager.GetObject("Clock_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_10 {
            get {
                object obj = ResourceManager.GetObject("Clock_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_11 {
            get {
                object obj = ResourceManager.GetObject("Clock_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_12 {
            get {
                object obj = ResourceManager.GetObject("Clock_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_13 {
            get {
                object obj = ResourceManager.GetObject("Clock_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_14 {
            get {
                object obj = ResourceManager.GetObject("Clock_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_15 {
            get {
                object obj = ResourceManager.GetObject("Clock_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clock_16 {
            get {
                object obj = ResourceManager.GetObject("Clock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS乱数工 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_cn {
            get {
                return ResourceManager.GetString("lang_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_en {
            get {
                return ResourceManager.GetString("lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Interface Customization File
        ///! lang_en.txt = English
        ///! lang_jp.txt = Japanese
        ///! lang_fr.txt = French
        ///! lang_de.txt = German
        ///! lang_es.txt = Spanish
        ///! lang_it.txt = Italian
        ///! lang_ko.txt = Korean
        ///! lang_cn.txt = Simplified Chinese
        ///! lang_zh.txt = Traditional Chinese
        ///! lang_pt.txt = Portuguese
        ///! Make sure that each edit has a &apos; = &apos; between Control name and new Text!
        ///! -----------------------------------------------------
        ///- DO NOT CHANGE THIS SECTION EXCEPT FORM NAME &amp; TITLE
        ///! MainForm = 3DS RN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lang_es {
            get {
                return ResourceManager.GetString("lang_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_ao {
            get {
                object obj = ResourceManager.GetObject("personal_ao", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] personal_sm {
            get {
                object obj = ResourceManager.GetObject("personal_sm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无性别
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///只有♂
        ///只有♀.
        /// </summary>
        internal static string text_Genderratio_cn {
            get {
                return ResourceManager.GetString("text_Genderratio_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderless
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂ Only
        ///♀ Only.
        /// </summary>
        internal static string text_Genderratio_en {
            get {
                return ResourceManager.GetString("text_Genderratio_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genderless
        ///♂1：♀1
        ///♂7：♀1
        ///♂3：♀1
        ///♂1：♀3
        ///♂1：♀7
        ///♂ Only
        ///♀ Only.
        /// </summary>
        internal static string text_Genderratio_es {
            get {
                return ResourceManager.GetString("text_Genderratio_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无道具
        ///不变之石
        ///红线
        ///力量负重-H
        ///力量护腕-A
        ///力量腰带-B
        ///力量镜-C
        ///力量束带-D
        ///力量护踝-S.
        /// </summary>
        internal static string text_Items_cn {
            get {
                return ResourceManager.GetString("text_Items_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item
        ///Everstone
        ///Destiny Knot
        ///Power Weight
        ///Power Bracer
        ///Power Belt
        ///Power Lens
        ///Power Band
        ///Power Anklet.
        /// </summary>
        internal static string text_Items_en {
            get {
                return ResourceManager.GetString("text_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Item
        ///Everstone
        ///Destiny Knot
        ///Power Weight
        ///Power Bracer
        ///Power Belt
        ///Power Lens
        ///Power Band
        ///Power Anklet.
        /// </summary>
        internal static string text_Items_es {
            get {
                return ResourceManager.GetString("text_Items_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －－－－－－－－－－
        ///
        ///神秘的地方
        ///
        ///遥远的地方
        ///
        ///１号道路
        ///好奥乐市郊
        ///１号道路
        ///
        ///３号道路
        ///
        ///２号道路
        ///
        ///卡拉蔚湾
        ///
        ///美乐美乐海
        ///
        ///好奥乐市
        ///海滩区
        ///好奥乐市
        ///商业区
        ///好奥乐市
        ///港口区
        ///利利小镇
        ///
        ///马哈罗山路
        ///
        ///马哈罗山路
        ///吊桥
        ///战争遗迹
        ///
        ///战争遗迹
        ///[~ 33]
        ///十克拉山丘
        ///
        ///十克拉山丘
        ///最深处的空洞
        ///好奥乐墓园
        ///
        ///美乐美乐花园
        ///
        ///通海洞穴
        ///
        ///树果园
        ///
        ///葱郁洞窟
        ///考验之地
        ///葱郁洞窟
        ///霸主居处
        ///４号道路
        ///
        ///５号道路
        ///
        ///６号道路
        ///
        ///７号道路
        ///
        ///８号道路
        ///
        ///９号道路
        ///
        ///豪诺豪诺度假地
        ///
        ///豪诺豪诺海滩
        ///
        ///阿卡拉花园
        ///
        ///欧哈纳镇
        ///
        ///慷待市
        ///
        ///可霓可市
        ///
        ///皇家大道
        ///
        ///回忆之丘
        ///
        ///欧哈纳牧场
        ///
        ///[~ 80]
        ///
        ///维拉火山公园
        ///
        ///维拉火山公园
        ///霸主居处
        ///潺潺之丘
        ///
        ///潺潺之丘
        ///霸主居处
        ///树荫丛林
        ///
        ///生命遗迹
        ///
        ///阿卡拉岛郊外
        ///
        ///[~ 96]
        ///[~ 97]
        ///[~ 98]
        ///[~ 99]
        ///地鼠隧道
        ///
        ///豪诺豪诺度假地
        ///
        ///皇家巨蛋 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_cn {
            get {
                return ResourceManager.GetString("text_Location_sm_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ——————
        ///
        ///Mystery Zone
        ///
        ///Faraway Place
        ///
        ///Route 1
        ///Hau’oli Outskirts
        ///Route 1
        ///
        ///Route 3
        ///
        ///Route 2
        ///
        ///Kala’e Bay
        ///
        ///Melemele Sea
        ///
        ///Hau’oli City
        ///Beachfront
        ///Hau’oli City
        ///Shopping District
        ///Hau’oli City
        ///Marina
        ///Iki Town
        ///
        ///Mahalo Trail
        ///
        ///Mahalo Trail
        ///Plank Bridge
        ///Ruins of Conflict
        ///
        ///Ruins of Conflict
        ///[~ 33]
        ///Ten Carat Hill
        ///
        ///Ten Carat Hill
        ///Farthest Hollow
        ///Hau’oli Cemetery
        ///
        ///Melemele Meadow
        ///
        ///Seaward Cave
        ///
        ///Berry Fields
        ///
        ///Verdant Cavern
        ///Trial Site
        ///Verdant Cavern
        ///Totem’s Den
        ///Route 4
        ///
        ///Rou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_en {
            get {
                return ResourceManager.GetString("text_Location_sm_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －
        ///
        ///Lugar misterioso
        ///
        ///Lugar lejano
        ///
        ///Ruta 1
        ///Afueras de Hauoli
        ///Ruta 1
        ///
        ///Ruta 3
        ///
        ///Ruta 2
        ///
        ///Bahía Kalae
        ///
        ///Mar de Melemele
        ///
        ///Ciudad Hauoli
        ///Paseo Marítimo
        ///Ciudad Hauoli
        ///Zona Comercial
        ///Ciudad Hauoli
        ///Puerto
        ///Pueblo Lilii
        ///
        ///Senda Mahalo
        ///
        ///Senda Mahalo
        ///Puente Colgante
        ///Ruinas de la Guerra
        ///
        ///Ruinas de la Guerra
        ///[~ 33]
        ///Colina Dequilate
        ///
        ///Colina Dequilate
        ///Caldera Remota
        ///Cementerio de Hauoli
        ///
        ///Jardines de Melemele
        ///
        ///Gruta Unemar
        ///
        ///Huerto de Bayas
        ///
        ///Cueva Sotobosque
        ///Sala de la Prueba
        ///Cueva  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_sm_es {
            get {
                return ResourceManager.GetString("text_Location_sm_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------
        ///
        ///神秘的地方
        ///
        ///遥远的地方
        ///
        ///朝香镇
        ///
        ///1号道路
        ///卡洛斯
        ///美川镇
        ///
        ///2号道路
        ///前进通道
        ///白檀森林
        ///
        ///3号道路
        ///开展通道
        ///白檀市
        ///
        ///4号道路
        ///花坛街道
        ///密阿雷市
        ///
        ///密阿雷道馆
        ///
        ///弗拉达利实验室
        ///
        ///5号道路
        ///斜坡通道
        ///古木镇
        ///
        ///休波努城堡
        ///
        ///6号道路
        ///宫殿林荫道
        ///香水宫殿
        ///
        ///7号道路
        ///河川直路
        ///遥香市
        ///
        ///8号道路
        ///城墙海岸
        ///古香镇
        ///
        ///9号道路
        ///刺刺山道
        ///对战古堡
        ///
        ///10号道路
        ///石柱之路
        ///石林镇
        ///
        ///11号道路
        ///明镜通道
        ///映身洞窟
        ///
        ///娑罗市
        ///
        ///精通塔
        ///
        ///12号道路
        ///牧草通道
        ///海翼市
        ///
        ///13号道路
        ///密阿雷荒野
        ///14号道路
        ///香薰林道
        ///香薰市
        ///
        ///宝贝球工厂
        ///
        ///15号道路
        ///褐棕通道
        ///雪风镇
        ///
        ///16号道路
        ///忧郁通道
        ///[~ 80]
        ///[~ 81]
        ///冰霜洞穴
        ///
        ///17号道路
        ///象牙猪路
        ///百刻市
        ///
        ///18号道路
        ///狭谷通道
        ///水涟镇
        ///
        ///19号道路
        ///巨谷通道
        ///映雪市
        ///
        ///20号道路
        ///迷幻森林
        ///神奇宝贝村庄
        ///
        ///21号道路
        ///最后通道 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_cn {
            get {
                return ResourceManager.GetString("text_Location_xy_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ——————
        ///
        ///Mystery Zone
        ///
        ///Faraway Place
        ///
        ///Vaniville Town
        ///
        ///Route 1
        ///Vaniville Pathway
        ///Aquacorde Town
        ///
        ///Route 2
        ///Avance Trail
        ///Santalune Forest
        ///
        ///Route 3
        ///Ouvert Way
        ///Santalune City
        ///
        ///Route 4
        ///Parterre Way
        ///Lumiose City
        ///
        ///Prism Tower
        ///
        ///Lysandre Labs
        ///
        ///Route 5
        ///Versant Road
        ///Camphrier Town
        ///
        ///Shabboneau Castle
        ///
        ///Route 6
        ///Palais Lane
        ///Parfum Palace
        ///
        ///Route 7
        ///Rivière Walk
        ///Cyllage City
        ///
        ///Route 8
        ///Muraille Coast
        ///Ambrette Town
        ///
        ///Route 9
        ///Spikes Passage
        ///Battle Chateau
        ///
        ///Route 10
        ///Menhir Trail
        ///Geo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_en {
            get {
                return ResourceManager.GetString("text_Location_xy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to －
        ///
        ///Lugar misterioso
        ///
        ///Lugar lejano
        ///
        ///Pueblo Boceto
        ///
        ///Ruta 1
        ///Sendero Boceto
        ///Pueblo Acuarela
        ///
        ///Ruta 2
        ///Vía del Avance
        ///Bosque de Novarte
        ///
        ///Ruta 3
        ///Senda Despejada
        ///Ciudad Novarte
        ///
        ///Ruta 4
        ///Senda del Parterre
        ///Ciudad Luminalia
        ///
        ///Torre Prisma
        ///
        ///Laboratorios Lysson
        ///
        ///Ruta 5
        ///Vía Repecho
        ///Pueblo Vánitas
        ///
        ///Castillo Caduco
        ///
        ///Ruta 6
        ///Alameda del Palacio
        ///Palacio Cénit
        ///
        ///Ruta 7
        ///Paseo de la Ribera
        ///Ciudad Relieve
        ///
        ///Ruta 8
        ///Muralla Costera
        ///Pueblo Petroglifo
        ///
        ///Ruta 9
        ///Paso de Rhyhorn
        ///Bastión Batalla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Location_xy_es {
            get {
                return ResourceManager.GetString("text_Location_xy_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勤奋
        ///怕寂寞
        ///勇敢
        ///固执
        ///顽皮
        ///大胆
        ///坦率
        ///悠闲
        ///淘气
        ///乐天
        ///胆小
        ///急躁
        ///认真
        ///爽朗
        ///天真
        ///内敛
        ///慢吞吞
        ///冷静
        ///害羞
        ///马虎
        ///温和
        ///温顺
        ///自大
        ///慎重
        ///浮躁.
        /// </summary>
        internal static string text_Natures_cn {
            get {
                return ResourceManager.GetString("text_Natures_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardy
        ///Lonely
        ///Brave
        ///Adamant
        ///Naughty
        ///Bold
        ///Docile
        ///Relaxed
        ///Impish
        ///Lax
        ///Timid
        ///Hasty
        ///Serious
        ///Jolly
        ///Naive
        ///Modest
        ///Mild
        ///Quiet
        ///Bashful
        ///Rash
        ///Calm
        ///Gentle
        ///Sassy
        ///Careful
        ///Quirky.
        /// </summary>
        internal static string text_Natures_en {
            get {
                return ResourceManager.GetString("text_Natures_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuerte
        ///Huraña
        ///Audaz
        ///Firme
        ///Pícara
        ///Osada
        ///Dócil
        ///Plácida
        ///Agitada
        ///Floja
        ///Miedosa
        ///Activa
        ///Seria
        ///Alegre
        ///Ingenua
        ///Modesta
        ///Afable
        ///Mansa
        ///Tímida
        ///Alocada
        ///Serena
        ///Amable
        ///Grosera
        ///Cauta
        ///Rara.
        /// </summary>
        internal static string text_Natures_es {
            get {
                return ResourceManager.GetString("text_Natures_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蛋
        ///妙蛙种子
        ///妙蛙草
        ///妙蛙花
        ///小火龙
        ///火恐龙
        ///喷火龙
        ///杰尼龟
        ///卡咪龟
        ///水箭龟
        ///绿毛虫
        ///铁甲蛹
        ///巴大蝶
        ///独角虫
        ///铁壳蛹
        ///大针蜂
        ///波波
        ///比比鸟
        ///大比鸟
        ///小拉达
        ///拉达
        ///烈雀
        ///大嘴雀
        ///阿柏蛇
        ///阿柏怪
        ///皮卡丘
        ///雷丘
        ///穿山鼠
        ///穿山王
        ///尼多兰
        ///尼多娜
        ///尼多后
        ///尼多朗
        ///尼多力诺
        ///尼多王
        ///皮皮
        ///皮可西
        ///六尾
        ///九尾
        ///胖丁
        ///胖可丁
        ///超音蝠
        ///大嘴蝠
        ///走路草
        ///臭臭花
        ///霸王花
        ///派拉斯
        ///派拉斯特
        ///毛球
        ///摩鲁蛾
        ///地鼠
        ///三地鼠
        ///喵喵
        ///猫老大
        ///可达鸭
        ///哥达鸭
        ///猴怪
        ///火暴猴
        ///卡蒂狗
        ///风速狗
        ///蚊香蝌蚪
        ///蚊香君
        ///蚊香泳士
        ///凯西
        ///勇基拉
        ///胡地
        ///腕力
        ///豪力
        ///怪力
        ///喇叭芽
        ///口呆花
        ///大食花
        ///玛瑙水母
        ///毒刺水母
        ///小拳石
        ///隆隆石
        ///隆隆岩
        ///小火马
        ///烈焰马
        ///呆呆兽
        ///呆壳兽
        ///小磁怪
        ///三合一磁怪
        ///大葱鸭
        ///嘟嘟
        ///嘟嘟利
        ///小海狮
        ///白海狮
        ///臭泥
        ///臭臭泥
        ///大舌贝
        ///刺甲贝
        ///鬼斯
        ///鬼斯通
        ///耿鬼
        ///大岩蛇
        ///催眠貘
        ///引梦貘人
        ///大钳蟹
        ///巨钳蟹
        ///霹雳电球
        ///顽皮雷弹
        ///蛋蛋
        ///椰蛋树
        ///卡拉卡拉 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_cn {
            get {
                return ResourceManager.GetString("text_Species_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_en {
            get {
                return ResourceManager.GetString("text_Species_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huevo
        ///Bulbasaur
        ///Ivysaur
        ///Venusaur
        ///Charmander
        ///Charmeleon
        ///Charizard
        ///Squirtle
        ///Wartortle
        ///Blastoise
        ///Caterpie
        ///Metapod
        ///Butterfree
        ///Weedle
        ///Kakuna
        ///Beedrill
        ///Pidgey
        ///Pidgeotto
        ///Pidgeot
        ///Rattata
        ///Raticate
        ///Spearow
        ///Fearow
        ///Ekans
        ///Arbok
        ///Pikachu
        ///Raichu
        ///Sandshrew
        ///Sandslash
        ///Nidoran♀
        ///Nidorina
        ///Nidoqueen
        ///Nidoran♂
        ///Nidorino
        ///Nidoking
        ///Clefairy
        ///Clefable
        ///Vulpix
        ///Ninetales
        ///Jigglypuff
        ///Wigglytuff
        ///Zubat
        ///Golbat
        ///Oddish
        ///Gloom
        ///Vileplume
        ///Paras
        ///Parasect
        ///Venonat
        ///Venomoth
        ///Diglett
        ///Dugtrio
        ///Meowth
        ///Persian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string text_Species_es {
            get {
                return ResourceManager.GetString("text_Species_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般
        ///格斗
        ///飞行
        ///毒
        ///地面
        ///岩石
        ///虫
        ///幽灵
        ///钢
        ///火
        ///水
        ///草
        ///电
        ///超能力
        ///冰
        ///龙
        ///恶
        ///妖精.
        /// </summary>
        internal static string text_Types_cn {
            get {
                return ResourceManager.GetString("text_Types_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Fighting
        ///Flying
        ///Poison
        ///Ground
        ///Rock
        ///Bug
        ///Ghost
        ///Steel
        ///Fire
        ///Water
        ///Grass
        ///Electric
        ///Psychic
        ///Ice
        ///Dragon
        ///Dark
        ///Fairy.
        /// </summary>
        internal static string text_Types_en {
            get {
                return ResourceManager.GetString("text_Types_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal
        ///Lucha
        ///Volador
        ///Veneno
        ///Tierra
        ///Roca
        ///Bicho
        ///Fantasma
        ///Acero
        ///Fuego
        ///Agua
        ///Planta
        ///Eléctrico
        ///Psíquico
        ///Hielo
        ///Dragón
        ///Siniestro
        ///Hada.
        /// </summary>
        internal static string text_Types_es {
            get {
                return ResourceManager.GetString("text_Types_es", resourceCulture);
            }
        }
    }
}
